-- DATABASE CREATION
CREATE DATABASE Hospital_Management_System;
USE Hospital_Management_System;

-- CREATE THE TABLE STRUCTURE

CREATE TABLE PATIENTS(
PATIENTS_ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENTS_NAME VARCHAR (100),
GENDER VARCHAR (10),
AGE INT,
PHONE VARCHAR (20),
CITY VARCHAR (30),
ADMISSION_DATE date
);

--  CREATE THE DOCTORS TABLE  

CREATE TABLE DOCTORS(
DOCTORS_ID INT PRIMARY KEY AUTO_INCREMENT,
DOCTORS_NAME VARCHAR(100),
SPECIALIZATION VARCHAR (100),
SALLARY DECIMAL(10,2),
EXPERIENCE_YEARS INT
);

--  CREATE THE DEPARTMENTS TABLE 
CREATE TABLE DEPARTMENTS(
DEPARTMENTS_ID INT PRIMARY KEY AUTO_INCREMENT,
DEPARTMENTS_NAME VARCHAR(100)
);
  
-- CREATE THE APPOINTMENTS TABLE

CREATE TABLE APPOINTMENTS(
APPOINTMENTS_ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENTS_ID INT,
DOCTORS_ID INT,
APPOINTMENT_DATE DATE,
APPOINTMENT_STATUS VARCHAR (100),
FOREIGN KEY (PATIENTS_ID) REFERENCES PATIENTS (PATIENTS_ID),
FOREIGN KEY (DOCTORS_ID) REFERENCES DOCTORS (DOCTORS_ID)
);

-- CREATE THE BILLING TABLE 

CREATE TABLE BILLING(
BILL_ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENTS_ID INT,
TOTAL_AMOUNT DECIMAL(10,2),
PAYMENT_STATUS VARCHAR(60),
FOREIGN KEY (PATIENTS_ID) REFERENCES PATIENTS (PATIENTS_ID)
);

--  CREATE THE MEDICINES TABLE

CREATE TABLE MEDICINES(
MEDICINE_ID INT PRIMARY KEY AUTO_INCREMENT,
MEDICINE_NAME VARCHAR (100),
COMPANY_NAME VARCHAR(50),
PRICE DECIMAL (10,2),
STOCK_QUANTITY INT
);

-- CREATE THE PRESCRIPTIONS TABLE 

CREATE TABLE PRESCRIPTIONS(
PRESCRIPTION_ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENTS_ID INT,
DOCTORS_ID INT,
MEDICINE_ID INT,
DOSAGE VARCHAR (100),
FOREIGN KEY (PATIENTS_ID) REFERENCES PATIENTS(PATIENTS_ID),
FOREIGN KEY (DOCTORS_ID) REFERENCES DOCTORS(DOCTORS_ID),
FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINES(MEDICINE_ID)
);

-- INSERT DATA

INSERT INTO PATIENTS 
(PATIENTS_NAME, GENDER, AGE, PHONE, CITY, ADMISSION_DATE)VALUE
('ANISHA KUMAR', 'MALE', 24, '9999999999', 'HYDERABAD', '2026-05-01'),
('RAHUL SHARMA', 'MALE', 30, '8888888888', 'DELHI', '2026-05-03'),
('PRIYA VERMA', 'FEMALE', 27, '7777777777', 'MUMBAI', '2026-05-04'),
('AMIT PATEL', 'MALE', 35, '6666666666', 'AHMEDABAD', '2026-05-05'),
('SNEHA REDDY', 'FEMALE', 22, '5555555555', 'BANGALORE', '2026-05-06'),
('VIKRAM SINGH', 'MALE', 45, '4444444444', 'CHENNAI', '2026-05-07'),
('POOJA JOSHI', 'FEMALE', 31, '3333333333', 'PUNE', '2026-05-08'),
('ROHAN DAS', 'MALE', 28, '2222222222', 'KOLKATA', '2026-05-09'),
('NEHA GUPTA', 'FEMALE', 26, '1111111111', 'JAIPUR', '2026-05-10'),
('ARJUN MEHTA', 'MALE', 40, '1234567890', 'LUCKNOW', '2026-05-11');

INSERT INTO DOCTORS
(DOCTORS_NAME, SPECIALIZATION, SALLARY, EXPERIENCE_YEARS)
VALUES
('DR. AMIT SINGH', 'CARDIOLOGIST', 120000, 10),
('DR. NEHA SHARMA', 'NEUROLOGIST', 150000, 12),
('DR. RAJ VERMA', 'ORTHOPEDIC', 100000, 8),
('DR. PRIYA PATEL', 'NEUROLOGIST', 80000, 11),
('DR. RAJESH KUMAR', 'PEDIATRICIAN', 110000, 7),
('DR. SUNITA RAO', 'NEUROLOGIST', 180000, 20),
('DR. VIKRAM MALHOTRA', 'NEUROLOGIST', 170000, 16),
('DR. ANJALI DESAI', 'CARDIOLOGIST', 80000, 5),
('DR. SURESH MISHRA', 'PEDIATRICIAN', 110000, 19),
('DR. KAVITA JOSHI', 'RADIOLOGIST', 80000, 20),
('DR. ROHAN MEHTA', 'PEDIATRICIAN', 190000, 23),
('DR. SNEHA REDDY', 'PSYCHIATRIST', 140000, 10),
('DR. MANOJ TIWARI', 'GENERAL PHYSICIAN', 170000, 11),
('DR. DIVYA NAIR', 'CARDIOLOGIST', 200000, 8),
('DR. ALOK GUPTA', 'GYNECOLOGIST', 130000, 11),
('DR. POOJA HEGDE', 'ORTHOPEDIC', 110000, 13),
('DR. SANJAY DUTT', 'NEUROLOGIST', 90000, 15),
('DR. MEERA KRISHNAN', 'NEUROLOGIST', 130000, 14),
('DR. HARISH CHOUDHARY', 'RADIOLOGIST', 120000, 4),
('DR. SWATI SHAH', 'GENERAL PHYSICIAN', 160000, 6),
('DR. VINAY SAXENA', 'GYNECOLOGIST', 90000, 20),
('DR. RITU KAPOOR', 'DERMATOLOGIST', 180000, 22),
('DR. ABHINAV SHUKLA', 'ONCOLOGIST', 170000, 9),
('DR. NIDHI AGRAWAL', 'NEUROLOGIST', 80000, 24),
('DR. PANKAJ TRIPATHI', 'PEDIATRICIAN', 200000, 12),
('DR. KIRAN BEDI', 'NEUROLOGIST', 110000, 6),
('DR. DEEPAK CHAWLA', 'GYNECOLOGIST', 120000, 17),
('DR. SHALINI VATS', 'ONCOLOGIST', 100000, 14),
('DR. GAURAV KAPOOR', 'ONCOLOGIST', 110000, 24),
('DR. PREETI SEN', 'DERMATOLOGIST', 190000, 24);

--  INSER DATA 

INSERT INTO DEPARTMENTS
(DEPARTMENTS_NAME)VALUE
('CARDIOLOGY'),
('NEUROLOGY'),
('ORTHOPEDIC'),
('PEDIATRICS'),
('DERMATOLOGY'),
('ONCOLOGY'),
('GYNECOLOGY'),
('RADIOLOGY'),
('PSYCHIATRY'),
('GASTROENTEROLOGY'),
('OPHTHALMOLOGY'),
('UROLOGY'),
('ENDOCRINOLOGY'),
('CARDIOTHORACIC'),
('ANESTHESIOLOGY'),
('EMERGENCY MEDICINE'),
('NEPHROLOGY'),
('PULMONOLOGY'),
('HEMATOLOGY'),
('RHEUMATOLOGY'),
('ENT OTO-RHINO-LARYNGOLOGY'),
('PATHOLOGY'),
('DENTAL SURGERY'),
('PHYSIOTHERAPY'),
('PLASTIC SURGERY'),
('GENERAL SURGERY'),
('GERIATRICS'),
('NEONATOLOGY'),
('IMMUNOLOGY'),
('INFECTIOUS DISEASES');

-- INSERT DATA 
 
INSERT INTO MEDICINES
(MEDICINE_NAME, COMPANY_NAME, PRICE, STOCK_QUANTITY)
VALUES
('PARACETAMOL', 'ABC PHARMA', 50, 200),
('DOLO 650', 'XYZ PHARMA', 80, 150),
('AMOXICILLIN', 'MEDICARE', 120, 100),
('IBUPROFEN', 'CIPLA LTD', 45, 300),
('METFORMIN', 'SUN PHARMA', 90, 500),
('ATORVASTATIN', 'LUPIN PHARMA', 150, 250),
('AMOXYCLAV', 'ALKEM LABS', 210, 120),
('AZITHROMYCIN', 'AZTEC PHARMA', 180, 180),
('PANTOPRAZOLE', 'INTAS PHARMA', 75, 400),
('MONTELUKAST', 'MANKIND PHARMA', 110, 220),
('CETIRIZINE', 'DR REDDYS', 35, 600),
('OMEPRAZOLE', 'TORRENT PHARMA', 65, 350),
('LOSARTAN', 'ALEMBIC PHARMA', 130, 190),
('AMLODIPINE', 'GLENMARK', 55, 280),
('METOPROLOL', 'ZYDUS CADILA', 95, 210),
('GABAPENTIN', 'AUBIN PHARMA', 240, 140),
('PREGABALIN', 'NEO HEALTHCARE', 280, 110),
('LEVOCETIRIZINE', 'MAX PHARMA', 40, 450),
('RANITIDINE', 'APEX LABS', 30, 500),
('CIPROFLOXACIN', 'BIOCON', 115, 130),
('CLOPIDOGREL', 'SANOFI', 160, 170),
('PIRACETAMOL', 'HERO PHARMA', 85, 90),
('TELMISARTAN', 'ERIS LIFESCIENCES', 140, 230),
('DICLOFENAC', 'REMEDY LABS', 50, 400),
('TRAMADOL', 'VISTA PHARMA', 190, 80),
('VITAMIN C', 'WELLNESS PHARMA', 25, 1000),
('ZINC VITAMIN', 'NUTRACARE', 45, 850),
('MULTIVITAMIN', 'LIFE PHARMA', 120, 600),
('CALCIUM D3', 'MATRIX LABS', 110, 400),
('B-COMPLEX', 'GENERICO', 35, 750);


-- VIEW ALL PATIENTS 
SELECT * FROM PATIENTS;

-- VIEW ALL DOCOTEOR
SELECT * FROM DOCTORS;

-- Find Doctors with Experience Above 10 Years
SELECT * FROM DOCTORS
WHERE EXPERIENCE_YEARS >10;

-- Total Billing Amount
SELECT SUM(TOTAL_AMOUNT)AS TOTAL_BILLING
FROM BILLING;

-- Average Doctor Salary
SELECT AVG(SALLARY) AS AVERAGE_SALARY
FROM DOCTORS;

--  JOIN Queries
-- Patient Appointment Report  
SELECT P.PATIENTS_NAME,
       D.DOCTORS_NAME, 
       A.APPOINTMENT_DATE,
       A.APPOINTMENT_STATUS
FROM APPOINTMENTS A
JOIN PATIENTS P ON A.PATIENTS_ID = P.PATIENTS_ID
JOIN DOCTORS D ON A.DOCTORS_ID = D.DOCTORS_ID;


-- PRESCRIPTIONS REPORT
SELECT
    P.PATIENTS_NAME,
    D.DOCTORS_NAME,
    M.MEDICINE_NAME,
    PR.DOSAGE
FROM PRESCRIPTIONS PR
JOIN PATIENTS P
ON PR.PATIENTS_ID = P.PATIENTS_ID
JOIN DOCTORS D
ON PR.DOCTORS_ID = D.DOCTORS_ID
JOIN MEDICINES M
ON PR.MEDICINE_ID = M.MEDICINE_ID;

--  GROUP BY QUERIES
-- Total Patients by City
SELECT CITY,
COUNT(PATIENTS_ID) AS TOTAL_PATIENTS
FROM PATIENTS
GROUP BY CITY;

--  Total Appointments by Doctor
SELECT DOCTORS_ID,
COUNT(APPOINTMENTS_ID) AS TOTAL_APPOINTMENTS 
FROM APPOINTMENTS
GROUP BY DOCTORS_ID; 

--   Subquery Example
-- Find Doctors with Salary Above Average
SELECT DOCTORS_NAME, 
SALLARY FROM DOCTORS
WHERE SALLARY >
( SELECT AVG(SALLARY) FROM DOCTORS);

-- VIEW 
-- Create Patient Billing Summary View
-- DROP VIEW IF EXISTS PATIENTS_BILLING_SUMMARY

CREATE VIEW PATIENTS_BILLING_SUMMARY AS
SELECT patients_name,
B.TOTAL_AMOUNT,
B.PAYMENT_STATUS
FROM PATIENTS P
JOIN BILLING B
ON P.PATIENTS_ID = B.PATIENTS_ID;

-- USE VIEW 
SELECT * FROM PATIENT_BILLING_SMMARY;
 
--  Stored Procedure
DELIMITER //
CREATE PROCEDURE GETPATIENTDETAILS(IN PID INT)
BEGIN SELECT * FROM PATIENTS
WHERE PATIENTS_ID = PID;
END // 
DELIMITER ;

-- Execute Procedure
CALL GETPATIENTSDETAILS(1);




